version: "3.7"

services:

    app:
        #build: .
        image: marcusms/microservicos-ex01-app
        container_name: app
        volumes: 
            - .:/var/www
        networks: 
            - app-network

    nginx:
        build: .docker/nginx
        container_name: nginx
        restart: always
        tty: true
        ports: 
            - 8000:80
        volumes:
            - .:/var/www
        networks: 
            - app-network

    data:
        image: mysql:5.7
        volumes:
            - laravel-mysql-data:/var/lib/mysql
        environment: 
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: laravel
        networks: 
            - app-network

    redis:
        image: redis:alpine
        expose:
            - 6379
        networks: 
            - app-network
    
volumes:
    laravel-mysql-data:

networks: 
    app-network: 
        driver: bridge